[options]
DisableDownloadTimeout
ParallelDownloads = 4

## https://packages.manjaro-sway.download
[manjaro-sway]
SigLevel = PackageRequired
Server = https://manjaro:manjaro@nexus.homelab.local/repository/manjaro-proxy-sway/stable/$arch

## https://forksystems.mm.fcix.net/manjaro
[core]
SigLevel = PackageRequired
Server = https://manjaro:manjaro@nexus.homelab.local/repository/manjaro-group/stable/$repo/$arch

## https://forksystems.mm.fcix.net/manjaro
[extra]
SigLevel = PackageRequired
Server = https://manjaro:manjaro@nexus.homelab.local/repository/manjaro-group/stable/$repo/$arch

## https://forksystems.mm.fcix.net/manjaro
[multilib]
SigLevel = PackageRequired
Server = https://manjaro:manjaro@nexus.homelab.local/repository/manjaro-group/stable/$repo/$arch